#!/bin/bash

export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1
export WLR_RENDERER_ALLOW_SOFTWARE=1
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=dwl
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1 # Removes server-side decorations in Qt apps

# Optional: set DPI, keyboard layout, or other session-specific variables
# export XCURSOR_SIZE=24
# export WLR_DRM_NO_ATOMIC=1

exec dbus-run-session dwl

